### ISSUE TITLE
Unsolved dependencies on Fedora 32

### ISSUE THREAD

**Issue by funnelfiasco** [RedHat-Eng-PGM/python-schedules-tools#11]
I'm going to guess this is a byproduct of the removal of (most) python2 packages from Fedora 32, but an attempt at upgrading gives me:

 Problem 6: problem with installed package python-schedules-tools-1:7.42-1.git20190605.1da7a26.fc31.noarch
  - package python-schedules-tools-1:7.42-1.git20190605.1da7a26.fc31.noarch requires python2.7dist(redis), but none of the providers can be installed
  - package fedora-obsolete-packages-32-44.noarch obsoletes python2-redis < 3.2.1-3 provided by python2-redis-3.2.1-2.fc31.noarch
  - problem with installed package fedora-obsolete-packages-31-41.noarch
  - python2-redis-3.2.1-2.fc31.noarch does not belong to a distupgrade repository
  - fedora-obsolete-packages-31-41.noarch does not belong to a distupgrade repository

Will I just need to carry a python2-redis package in a COPR repo or is there something else we can do to fix this?

**Comment by pavel-slama** [comment]
I'll work on this in next 2 weeks, in the meantime, you can try installing it from pypi (using python2-pip) - into virtualenv

https://pypi.org/project/schedules-tools/

**Comment by pavel-slama** [comment]
Fixed - 7.42 was pretty old - newer versions don't require redis
Tested upgrade to new py2/py3 rpms
