### ISSUE TITLE
RFE: Sort by date in flat and milestone views

### ISSUE THREAD

**Issue by funnelfiasco** [RedHat-Eng-PGM/python-schedules-tools#4]
When generating HTML output in flat or milestone view, it would be helpful to (at least optionally) sort the tasks into chronological order. As seen in [this example](https://bcotton.fedorapeople.org/f-32-key-tasks-flat.html), tasks seem to be ordered by their order in Smartsheet. Sometimes this is easily fixable in the source (e.g. items 1-3) but sometimes it's not (e.g. items 18-19).

**Comment by pavel-slama** [comment]
Hi - planned for next sprint (to be delivered by May 28)

**Comment by likeon** [comment]
@funnelfiasco the feature is implemented and published on pypi.

You can apply sorting by date by adding `--sort=date_start` to schedule-convert console cli arguments.
